### GET request to create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "kafka testing",
  "email": "test10789_kafka@example.com",
  "address": "123 Main St, Cityville",
  "dateOfBirth": "2000-01-01",
  "registeredDate": "2023-10-01"
}

###